"""empty message

Revision ID: e26fc5afadeb
Revises: 
Create Date: 2024-03-31 18:17:50.467023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e26fc5afadeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('big',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Season', sa.Integer(), nullable=True),
    sa.Column('Episode', sa.Integer(), nullable=True),
    sa.Column('Scene', sa.Integer(), nullable=True),
    sa.Column('Line', sa.Integer(), nullable=True),
    sa.Column('Location', sa.Text(), nullable=True),
    sa.Column('Action', sa.Text(), nullable=True),
    sa.Column('Words', sa.Text(), nullable=True),
    sa.Column('Speaker', sa.Text(), nullable=True),
    sa.Column('Listener', sa.Text(), nullable=True),
    sa.Column('Result', mysql.LONGTEXT(), nullable=True),
    sa.Column('batchno', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batchno', 'Season', 'Episode', 'Scene', 'Line', name='unique_index_constraint')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=768), nullable=True),
    sa.Column('password', sa.String(length=768), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user')
    op.drop_table('big')
    # ### end Alembic commands ###
